### ISSUE TITLE
Bottom Board.

### ISSUE THREAD

**Issue by chuckcaley** [derekfountain/zx-spectrum-pico-interface-one#10]
There's no files for the bottom board?
Are you going to release them or are you still working on them?
TIA

**Comment by derekfountain** [comment]
Everything is complete and released. What "files" are you referring to?

**Comment by chuckcaley** [comment]
The UI daugther board is there but the board with the pico's on. We also have the parts listed on the main page but there is no info on the main board with the pico's and sd card etc. eg. board/schematic files or gerbers

**Comment by chuckcaley** [comment]
My bad. I have found them Wasn't expexting the files to be in the srom folder. Sorry for the trouble.

**Comment by derekfountain** [comment]
No problem, I'm keen to hear from people who are interested.

I've updated the README with a bit of guidance for anyone else who is lost. :)
